[package]
name = "metatorio"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
dotenv = "0.15.0"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
